name: MacOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        shell: bash
        run: |
          ./gradlew --info --stacktrace packageDmg

      - name: List build directory
        shell: bash
        run: |
          echo "Listing DMG directory content:"
          ls -la "$GITHUB_WORKSPACE/composeApp/build/compose/binaries/main/dmg/"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: timetable-installer
          path: ${{ github.workspace }}/composeApp/build/compose/binaries/main/dmg/*.dmg
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-logs
          path: |
            ${{ github.workspace }}/composeApp/build/compose/logs/
            ${{ github.workspace }}/composeApp/build/reports/
          if-no-files-found: warn
